### ISSUE TITLE
Rate Limit exceed on Portal 

### ISSUE THREAD

**Issue by aneesh08192** [anburocky3/inssia-image-downloader#2]
Rate limit exceeded in portal - add proxy for each page.
And please add parallel downloading. Thanks.

![image](https://user-images.githubusercontent.com/92361323/194773391-837652e8-d291-4c13-8e7a-72a55d8be4c0.png)
![image](https://user-images.githubusercontent.com/92361323/194773412-20a1c3ee-4596-4d1b-881f-a83337185ab6.png)

**Comment by anburocky3** [comment]
**Update:** The reason it was throwing the error is because of file not available to download. 

Now, we have improved a bit. Now, it will show errors like these:

![image](https://user-images.githubusercontent.com/15264938/194778184-088961b3-4c63-41d3-bcfa-3dadb10f430b.png)

Remember, it will only download when it finds. if the image is not available, it will just throw error
```
 ---ERROR: - Image Could not be retrieved: 
```

**Comment by anburocky3** [comment]
@aneesh08192 Fixed in the latest code. Get the latest code and retry it again. 

https://github.com/anburocky3/inssia-image-downloader/releases/tag/v1.1
